### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by RumataEstor** [racer-rust/emacs-racer#1]
I tried to install racer-emacs from melpa (20150830.257) and have following error while it is compiled:
```
racer.el:197:1:Error: Wrong number of arguments:
(lambda (form list) "Anaphoric form of `-filter'." (let ((r (make-symbol "result"))) (list (quote let) (list r) (list (quote --each) list (list (quote when) form (list (quote !cons) (quote it) r))) (list (quote nreverse) r)))), 1
```

Also when I try to use racer-find-definition I see `Symbol's function definition is void: -let`.

Feels like I lack some library but I don't know which.

**Comment by fbergroth** [comment]
Right, the version of dash we depend on is too old. Try updating dash.

**Comment by ane** [comment]
Fixed by d18da641fb2ea7178a8ae042b8227f22df6d524f.

**Comment by RumataEstor** [comment]
I updated dash to melpa version 20150829.433 and still have the same problem.

**Comment by ane** [comment]
Did you also update the racer package?

**Comment by RumataEstor** [comment]
I did. I retryed it once more and it did work like a charm. Thanks for help!
